#%RAML 1.0 NamedExample
- business: "MuleSoft"
  street: "77 Geary St"
  suite: ""
  city: "San Francisco"
  state: "CA"
  postal: "94108"
  country: "US"
- business: "MuleSoft"
  street: "77 Geary St"
  suite: "Flr 4"
  city: "San Francisco"
  state: "CA"
  postal: "94108"
  country: "US"